name: Automated update of known-issue suppression

on:
  pull_request:
    branches:
      - master
  schedule:
    # At 12 midnight, 7am and 5pm
    - cron: "0 0,7,17 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.HMCTS_GITHUB_EXUI_APP_ID }}
          private_key: ${{ secrets.HMCTS_GITHUB_EXUI_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate-token.outputs.token }}
          ref: master
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: yarn install
      - name: Run automated update of known-issue suppression
        run: yarn update-audit-known-issues
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          skip_dirty_check: false
          commit_message: "Automated update of known-issue suppression"
          branch: master
